github: TobiasBg
patreon: TobiasBg
custom:
  - https://paypal.me/TobiasBg
  - https://venmo.com/TobiasBg
  - https://www.buymeacoffee.com/TablePress
  - https://amazon.com/wishlist/3CSH3SBZS62NO
  - https://tablepress.org/donate/
