<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitb6c36c6c644c58ffd85f164a56a3410a
{
	private static $loader;

	public static function loadClassLoader($class)
	{
		if ('Composer\AutoloadTablePress\ClassLoader' === $class) {
			require __DIR__ . '/ClassLoader.php';
		}
	}

	/**
	 * @return \Composer\AutoloadTablePress\ClassLoader
	 */
	public static function getLoader()
	{
		if (null !== self::$loader) {
			return self::$loader;
		}

		require __DIR__ . '/platform_check.php';

		spl_autoload_register(array('ComposerAutoloaderInitb6c36c6c644c58ffd85f164a56a3410a', 'loadClassLoader'), true, true);
		self::$loader = $loader = new \Composer\AutoloadTablePress\ClassLoader(\dirname(__DIR__));
		spl_autoload_unregister(array('ComposerAutoloaderInitb6c36c6c644c58ffd85f164a56a3410a', 'loadClassLoader'));

		require __DIR__ . '/autoload_static.php';
		call_user_func(\Composer\Autoload\ComposerStaticInitb6c36c6c644c58ffd85f164a56a3410a::getInitializer($loader));

		$loader->setClassMapAuthoritative(true);
		$loader->register(true);

		return $loader;
	}
}
