<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitbdc74b663ea7898186a6e4b25f1f64c8
{
	private static $loader;

	public static function loadClassLoader($class)
	{
		if ('Composer\AutoloadTablePress\ClassLoader' === $class) {
			require __DIR__ . '/ClassLoader.php';
		}
	}

	/**
	 * @return \Composer\AutoloadTablePress\ClassLoader
	 */
	public static function getLoader()
	{
		if (null !== self::$loader) {
			return self::$loader;
		}

		require __DIR__ . '/platform_check.php';

		spl_autoload_register(array('ComposerAutoloaderInitbdc74b663ea7898186a6e4b25f1f64c8', 'loadClassLoader'), true, true);
		self::$loader = $loader = new \Composer\AutoloadTablePress\ClassLoader(\dirname(__DIR__));
		spl_autoload_unregister(array('ComposerAutoloaderInitbdc74b663ea7898186a6e4b25f1f64c8', 'loadClassLoader'));

		require __DIR__ . '/autoload_static.php';
		call_user_func(\Composer\Autoload\ComposerStaticInitbdc74b663ea7898186a6e4b25f1f64c8::getInitializer($loader));

		$loader->setClassMapAuthoritative(true);
		$loader->register(true);

		return $loader;
	}
}
