name: PHPUnit Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      # Any change to a PHP file should run checks.
      - '**.php'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures PHPUnit. Changes could affect the outcome.
      - 'phpunit.xml.dist'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths:
      # Any change to a PHP file should run checks.
      - '**.php'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures PHPUnit. Changes could affect the outcome.
      - 'phpunit.xml.dist'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  schedule:
    - cron: '45 3 * * SUN'
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # Runs the PHPUnit tests for TablePress.
  phpunit:
    name: WP ${{ matrix.wp }}${{ matrix.multisite && ' multisite' || '' }}, PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_tests
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    strategy:
      fail-fast: false
      matrix:
        wp:
          - trunk
          - '6.0'
          - '5.9'
          - '5.8'
        php:
          - '8.2'
          - '8.1'
          - '8.0'
          - '7.4'
          - '7.3'
          - '7.2'
          - '7.1'
          - '7.0'
          - '5.6'
        multisite: [ false, true ]
        exclude:
          # Testing with PHP 8+ on WP 5.8 fails due to PHPUnit incompatibilities.
          - wp: '5.8'
            php: '8.2'
          - wp: '5.8'
            php: '8.1'
          - wp: '5.8'
            php: '8.0'
    env:
      PLUGIN_DIR: ./src/wp-content/plugins/tablepress

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709 # v2.21.2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log debug information
        run: |
          php --version
          composer --version
          git --version

      - name: Checkout specified version of the WordPress development repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          repository: WordPress/WordPress-develop
          ref: ${{ matrix.wp }}

      - name: Set up the WordPress unit tests configuration file
        run: |
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php
          sed -i "s/localhost/127.0.0.1:3306/" wp-tests-config.php

      - name: Checkout TablePress repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          path: ${{ env.PLUGIN_DIR }}

      - name: Manually install PHPUnit when running WP 5.8, depending on the PHP version
        if: ${{ matrix.wp == '5.8' }}
        working-directory: ${{ env.PLUGIN_DIR }}
        run: composer require --dev "phpunit/phpunit:^5.7.21 || ^6.5 || ^7.5" --no-update

      - name: Install Composer dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # v2.1.0
        with:
          composer-options: "--working-dir=${{ env.PLUGIN_DIR }}${{ ( matrix.php == '8.1' || matrix.php == '8.2' ) && ' --ignore-platform-reqs' || '' }}"

      - name: Make Composer packages available globally
        working-directory: ${{ env.PLUGIN_DIR }}
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Run PHPUnit
        env:
          WP_TESTS_DIR: ${{ github.workspace }}/tests/phpunit/
          WP_VERSION: ${{ matrix.wp }}
          WP_MULTISITE: ${{ matrix.multisite && '1' || '0' }}
        working-directory: ${{ env.PLUGIN_DIR }}
        continue-on-error: ${{ matrix.php == '8.2' }} # WP still runs into dynamic property deprecations.
        run: phpunit --verbose --exclude-group=ms-${{ matrix.multisite && 'excluded' || 'required' }}

      # composer.json will have been modified on WP 5.8, where PHPUnit is installed.
      - name: Ensure version-controlled files are not modified or deleted
        working-directory: ${{ env.PLUGIN_DIR }}
        run: git diff --exit-code${{ ( matrix.wp == '5.8' ) && ' -- . ":!composer.json"' || '' }}
