name: PHPUnit Tests

permissions:
  contents: read

on:
  push:
    branches:
      - master
    paths:
      # Any change to a PHP file should run checks.
      - '**.php'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures PHPUnit. Changes could affect the outcome.
      - 'phpunit.xml.dist'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - master
    paths:
      # Any change to a PHP file should run checks.
      - '**.php'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures PHPUnit. Changes could affect the outcome.
      - 'phpunit.xml.dist'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  schedule:
    - cron: '45 3 * * SUN'
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # Runs the PHPUnit tests for TablePress.
  phpunit:
    name: WP ${{ matrix.wp }}${{ matrix.multisite && ' multisite' || '' }}, PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_tests
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    strategy:
      fail-fast: false
      matrix:
        wp:
          - master
          - '5.8'
          - '5.7'
          - '5.6'
        php:
          - '7.4'
          - '7.3'
          - '7.2'
          - '7.1'
          - '7.0'
          - '5.6'
        multisite: [ false, true ]
        include:
          - wp: master
            php: '8.2'
          - wp: master
            php: '8.1'
          - wp: master
            php: '8.0'
    env:
      WP_VERSION: ${{ matrix.wp }}
      WP_DEVELOP_DIR: /tmp/wordpress

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer
          extensions: mysql

      - name: Manually install PHPUnit when running WP <= 5.8, depending on the PHP version
        if: ${{ matrix.wp != 'master' }}
        run: composer require --dev "phpunit/phpunit:^5.7.21 || ^6.5 || ^7.5" --no-install

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: ${{ ( matrix.php == '8.1' || matrix.php == '8.2' ) && '--ignore-platform-reqs' || '' }}

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Log debug information
        run: |
          php --version
          composer --version
          git --version

      - name: Clone the WordPress development repository
        run: git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR

      - name: Setup WordPress unit tests
        run: |
          export PLUGIN_SLUG=$(basename $(pwd))
          export PLUGIN_SLUG_LC=${PLUGIN_SLUG,,}
          export PLUGIN_DIR="$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG_LC"
          echo "PLUGIN_DIR=$PLUGIN_DIR" >> $GITHUB_ENV
          cd ..
          cp -r "$PLUGIN_SLUG" "$PLUGIN_DIR"

      - name: Set up the WordPress unit tests configuration file
        working-directory: ${{ env.WP_DEVELOP_DIR }}
        run: |
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php
          sed -i "s/localhost/127.0.0.1:3306/" wp-tests-config.php

      - name: Run PHPUnit
        env:
          WP_TESTS_DIR: ${{ env.WP_DEVELOP_DIR }}/tests/phpunit/
          WP_MULTISITE: ${{ matrix.multisite && '1' || '0' }}
        working-directory: ${{ env.PLUGIN_DIR }}
        run: phpunit --exclude-group=ms-${{ matrix.multisite && 'excluded' || 'required' }}

      # composer.json will have been modified on WP <= 5.8, where PHPUnit is installed.
      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code${{ matrix.wp != 'master' && ' -- . ":!composer.json"' || '' }}
