name: Deploy to wordpress.org Repository

on:
  # Deploy to wordpress.org when a production release is created.
  release:
    types: [ released ]
  # Do a "dry run" (without comming to SVN) when the workflow is manually triggered.
  workflow_dispatch:

jobs:

  deploy_to_wordpress_org:
    name: Deploy to wordpress.org${{ github.event_name == 'workflow_dispatch' && ' (dry run)' || '' }}
    if: github.repository == 'TablePress/TablePress'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout TablePress repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
          dry-run: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ vars.SLUG }}

      - name: Get plugin version and rename ZIP file
        id: get-version
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          SLUG: ${{ vars.SLUG }}
          ZIPPATH: ${{ steps.deploy.outputs.zip-path }}
        run: |
          VERSION=$(awk '/Stable tag: /{print $NF}' readme.txt)
          echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
          mv ${ZIPPATH} ${GITHUB_WORKSPACE}/${SLUG}.${VERSION}.zip

      - name: Upload release ZIP file
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          files: ${{ github.workspace }}/${{ vars.SLUG }}.${{ steps.get-version.outputs.version }}.zip
