name: Update WordPress.org Plugin Assets (Screenshots, readme.txt)

on:
  # Deploy plugin assets to wordpress.org when the workflow is manually triggered.
  workflow_dispatch:

jobs:

  update_assets:
    name: Update WordPress.org Plugin Assets
    if: github.repository == 'TablePress/TablePress'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TablePress repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ vars.SLUG }}
          IGNORE_OTHER_FILES: true
